import { mockAttendanceSessions, mockChoirMembers, mockStudents } from '@/lib/mock-data';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import Image from 'next/image';
import { format } from 'date-fns';
import { Check, X } from 'lucide-react';

export default function RegisterReport() {
    const schoolLogo = PlaceHolderImages.find(img => img.id === 'school_logo');
    const activeMembers = mockChoirMembers
        .filter(cm => cm.status === 'active')
        .map(cm => mockStudents.find(s => s.admission_number === cm.admission_number))
        .filter(Boolean);

    const sessions = mockAttendanceSessions;

  return (
    <div className="report-preview-landscape mx-auto bg-white p-8 rounded-lg shadow-lg" id="register-report">
        <header className="flex items-center justify-between border-b pb-4">
            <div className="space-y-1">
                <h2 className="text-2xl font-bold text-gray-800">Springfield High School</h2>
                <p className="font-headline text-lg text-gray-600">Full Choir Attendance Register</p>
            </div>
            {schoolLogo && (
            <Image
                src={schoolLogo.imageUrl}
                alt={schoolLogo.description}
                width={80}
                height={80}
                className="rounded-full"
                data-ai-hint={schoolLogo.imageHint}
            />
            )}
        </header>
        <div className="text-sm text-gray-600 mt-2">
            <strong>Date Range:</strong> {format(sessions[0].date, 'MMM dd, yyyy')} - {format(sessions[sessions.length-1].date, 'MMM dd, yyyy')}
        </div>

        <section className="mt-6">
            <Table className="report-table">
                <TableHeader>
                    <TableRow>
                        <TableHead className="w-[100px]">Adm. No.</TableHead>
                        <TableHead className="min-w-[150px]">Full Name</TableHead>
                        <TableHead className="w-[100px]">Class</TableHead>
                        {sessions.map(session => (
                            <TableHead key={session.id} className="text-center rotate-[-45deg] !h-24 !pb-2 !align-bottom">
                                <span className="whitespace-nowrap">{format(session.date, 'MMM dd')}</span>
                            </TableHead>
                        ))}
                        <TableHead className="text-center font-bold">Total Present</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {activeMembers.map(member => {
                        if (!member) return null;
                        let presentCount = 0;
                        return (
                            <TableRow key={member.admission_number}>
                                <TableCell>{member.admission_number}</TableCell>
                                <TableCell>{member.first_name} {member.last_name}</TableCell>
                                <TableCell>{member.class}</TableCell>
                                {sessions.map(session => {
                                    const isPresent = session.attendance_map[member.admission_number];
                                    if(isPresent) presentCount++;
                                    return (
                                        <TableCell key={`${member.admission_number}-${session.id}`} className="text-center">
                                            {isPresent === true && <Check className="h-4 w-4 text-green-600 mx-auto" />}
                                            {isPresent === false && <X className="h-4 w-4 text-red-600 mx-auto" />}
                                        </TableCell>
                                    )
                                })}
                                <TableCell className="text-center font-bold">{presentCount}</TableCell>
                            </TableRow>
                        )
                    })}
                </TableBody>
            </Table>
        </section>

        <footer className="mt-8 pt-4 text-sm text-gray-500 border-t">
            <div className="flex justify-between">
                <p>Prepared by: Choir Director (auto-generated)</p>
                <p>Page 1 of 1</p>
            </div>
            <p className="text-center text-xs mt-4">Generated by ChoirMaster on {format(new Date(), 'PPp')}</p>
        </footer>
    </div>
  );
}
